### PR TITLE
(Victory) Road to 2.0

### LINKED ISSUE #16: feat: Add support for gen 2
Could also mean support for IR gifts, which would mean it could act as an IR demo

### LINKED ISSUE #23: Require hold Back to exit
### Describe the bug.

On more than one occasion, when attempting to modify a traded Pokemon, I've just completely exited the app on accident thereby losing that specific Pokemon to the Ether.

From the main menu, require a hold of the Back button, or maybe a prompt (or both?) to close the app completely.

### Reproduction

NA

### Target Framework

_No response_

### Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kbembedded**
Spinning up to get gen ii support going. Along with that I'm wanting to implement Mystery Gift and if I feel like it, Pokemon TCG Card Pop! support. Along with incorporating gen ii sprites, I'm hoping to see some of the other sprites get some clean up.

This is still a WIP and will be a Draft until its ready. I'm leaving it open here in case anyone wants to test or start playing with this before its fully done.

  - Gen II Support  
    - [x] Add sprites (complete, not yet committed)
    - [x] Add movesets  
    - [x] ~~Add types~~ Types are not exchanged as part of trade in gen ii  
    - [x] Add items  
    - [x] Modify gender  
    - [x] Modify shininess  
    - [x] Modify Unown form  
    - [x] ~~Add Mystery Gift~~ (Will implement later)  
  - Layout  
    - [x] Reorg menus  
      - [x] Create main menu to select trade target  
        - [x] Gen I  
          - [x] Gen I trades currently broken (as of 20240307), patch list is broken.
        - [x] Gen II  (resolves #16)
          - [x] Gen II trades currently broken (as of 20240307), jumps from ready to waiting to ready. This was previously working. I _think_ this is an issue with my game file, it appeared after I messed with giving Mail to pokemon to hold. 20240311: Working for me in my test branch, others still potentially have issues.
        - [x] ~~Gen II Mystery Gift~~ (Will implement later)  
        - [x] Select Pinout  
    - [x] Require confirmation of exit (maybe only do this after a trade has been done? Mostly to prevent accidentally backing out) (resolves #23)
      - [x] Would love to add a sad pikachu icon to this if there is time/space  
    - [x] Fix Select view to allow full pokemon sprite to be visible
    - [x] Fix Trade view to allow full pokemon sprite to be visible (this may not work)  
  - Code refactor and shrink  
    - [x] Reduce clutter of accessing parts of the pokemon trade struct  
    - [x] Support dynamic access of pokemon trade structs for either gen i or gen ii
    - [x] Can likely pack structs  
    - [x] ~~Investigate string compression possibilities~~ Due to the nature of the strings, i.e. names of pokemon, items with abbreviations, lack of repetition of strings, the savings here is minimal given the overhead involved with decompressing.  
    - [x] Optimize the lazily slapped together functions  
    - [x] Move large const data structs in to their own file(s)  
    - [x] ~~Compress sprite icons if they are not already (See "Sprite Work")~~ Icons are indeed compressed.  
    - [x] ~~Rework Select Pokemon alloc to use an anonymous pointer like Trade now does~~ Not going to target it, if I end up _having_ to touch it then I will, but for now leaving this alone.  
    - [x] See about reusing some of the Modules to reduce code footprint  
      - e.g. pokemon name, trainer name, both have similar restrictions, could collapse those to the same set
    - [x] I believe there is a small memory leak somewhere, fix it.
  - Sprite Work  
    - [x] Auto-generated sprites arn't great, clean up and consider some more customized pixel art  (90% complete as of 20240513)
    - [x] ~~Move to using compressed bitmaps rather than icons (currently, Icons take up \~45kbyte)~~ Icons are compressed.  
    - [x] Can we store sprites on SD card and load them as needed? How to distribute that? Looks like this is possible  
      - [x] ~~Need to find a way to nicely dynamically load/unload these sprites. If on-demand is too non-responsive, the consider loading in chunks of 10+, and load a couple of chunks ahead of time so there is a good window of responsiveness.~~ Testing has found that there is no impact to responsiveness when loading each sprite on-demand.  
  - Optional Goals (read: if I feel like working on them)  
    - [x] ~~Save pokemon to SD card~~ Not interested in doing this ATM.  
    - [x] ~~Some logic to "harvest" GB trainer name and number (I think this would require a trade as OT Num isn't transferred. Requiring a trade is a lot of hassle and is more or less already implemented)~~ This would require at least starting a trade, but in a way that wouldn't clobber the current pokemon -OR- completing a trade with a junk pokemon, transforming it in to what the user wants, and it will pull in the OT ID/Name.  
    - [x] ~~Sprite animations (doable, but, may require more space than we have available at the moment)~~ Maybe another time  
    - [x] ~~Add Pokemon TCG Card Pop! support~~  
    - [x] ~~Add option to select the default pinout that the tool should use~~ Doing this correctly is going to require a bit of a rewrite to the pin selection menu anyway. Default/Original is going to be most common, so that is good enough for now.  
  - [x] Fix issue with malveke ext1 clock interrupt breaking interface buttons ([flipper-gblink issue](https://github.com/kbembedded/flipper-gblink))
    - [x] ~~Wrap MALVEKE detect in debug defines to not break debug when detecting MALVEKE's with Original pinout~~ Per conversations, the app will default to `Original` pinout and `MALVEKE` will need to be separately selected.

### CODE REVIEW

**Comment by EstebanFuentealba** [comment]
Great roadmap, you're awesome @kbembedded  . 

Regarding the images, we could try testing something like https://github.com/flipperdevices/flipperzero-firmware/tree/dev/applications/examples/example_apps_assets to see if we can free up some memory.

**Comment by kbembedded** [comment]
Fairly large assorted updates.

Most of this work so far is focused on cleaning up how all aspects of the trade block are accessed to make it more generic. This should make it easier to plug in gen ii data without having to modify the existing scenes/views. There are now accessor functions for getting and setting pretty much all of the data. This may still see some cleanup down the road if I feel like it, but I think this is good enough for now to start focusing on feature adding.

MALVEKE detection might be a bit broken right now, but that will get cleaned up and checked again later as there is still some more work that needs to be done there.

**Comment by kbembedded** [comment]
Had a different project come up that took priority, however I'm back at this now and am hoping to have gen ii trades functional soon.

If anyone out there has a MALVEKE, and a copy of Gold that is far enough in to have mystery gift, if you could send me the save file for that, that would be great :D  I am not far enough in to Gold to get the mystery gift and I'm not sure how long it will take me playing casually.

**Comment by EstebanFuentealba** [comment]
Hi Kris, great job so far! I haven't had a chance to try it out yet as I'm just getting back from vacation, but I might dive back into the projects today.

What do you think about splitting the PR into several smaller ones? For instance, we could separate "Mystery Gift," "TCG Card Pop," "Sprite animations," and "Customized pixel art" to get a playable version sooner.

I could also help with generating images for the second-generation Pokémon, similar to what I did for the first generation.

What do you think?

Best regards,

**Comment by kbembedded** [comment]
> Hi Kris, great job so far! I haven't had a chance to try it out yet as I'm just getting back from vacation, but I might dive back into the projects today.

Thanks!


> What do you think about splitting the PR into several smaller ones? For instance, we could separate "Mystery Gift," "TCG Card Pop," "Sprite animations," and "Customized pixel art" to get a playable version sooner.

I left it as one big one for a couple of reasons.
1) I had to rip up and rewrite a bunch of code because of how specific the app was originally to gen I, notice there are 47 files changed so far, that's basically every file in the whole repo. I also took that opportunity to reel back in a lot of the hacky things I left in place (before introducing more 🙃). And I'm debating also changing up how I handle the data structures in the background just to make the code more manageable as all of the data handling ballooned (though that _could_ wait for a later release, if I can shave off final binary size, thats going to be helpful in getting all of the sprites to fit).
2) I wouldn't consider gen II support complete until it also supports Mystery Gift as that is a part of that generation.
3) Sprite animations probably won't make it in to this PR. Not everything I have listed above will, and I was planning on splitting those out. Card Pop! may also not make it in this anyway.
4) I've had a handful of people reach out and ask for builds which are easy enough to provide, and let them know that things may still be broken. So, while not getting a public release, those who are interested and who have been interacting with me on this are getting test builds and providing good feedback/testing.
5) Personally, I want the custom sprites to be a part of this release. It might delay it a bit, but, they are being worked on in the background and about 20% of them are complete at this moment. Once I'm done with code and ready to start bringing it all together, I will also step in and help with the sprite art. The auto generated sprites just don't do it for me after seeing what is possible lol.
 

> I could also help with generating images for the second-generation Pokémon, similar to what I did for the first generation.
> 
> What do you think?

A friend of mine already offered and is looking in to this, I might accept it as a placeholder, but I don't want to open this PR until the custom sprite art is done.

**Comment by kbembedded** [comment]
Loading sprites from SD looks like it will be functional with almost no impact on the application responsiveness. Currently a WIP but will make its way here soon.

In the home stretch of getting all of the features implemented. Still need to do some cleanup and tuning, but, this should be ready soon™

**Comment by EstebanFuentealba** [comment]
Perhaps in future versions, it would be beneficial to apply inheritance to avoid having so many conditions for GENI and GENII.

For instance:
```cpp
trading.parser(new PokemonTradingParserGenerationI(context));
// or
trading.parser(new PokemonTradingParserGenerationII(context));
// ...
trading.tradePending(); // Call the "tradePending" function based on the initialized object.
```

```cpp
class PokemonTradingParser {
  PokemonTradingParser(void *context);
  // ...
  void tradeReset();
  void tradeInit();
  void tradeRandom();
  void tradePending();
  void tradePatchHeader();
  void tradePatchData();
  // ... other functions
}

class PokemonTradingParserGenerationI : public PokemonTradingParser {
  // override necessary methods
  void tradePending() override;
}

class PokemonTradingParserGenerationII : public PokemonTradingParser {
  // override necessary methods
  void tradePending() override;
}
```

**Comment by kbembedded** [comment]
I'm more fluent in C than C++, and when it comes to the trade protocol, gen I and II are extremely similar with a few exceptions. Right now, what I've done is hacky, and won't make it to the final PR without cleanup. By the end of it, there should only be 1, maybe two generation checks in the trade state machine for the points that greatly differ.

What is currently worse than trade when it comes to per generation conditionals is the data structure handling/setup; which I also have plans to rework before the final PR is opened.

If you want to move things to use C++ constructs, you're more than welcome to. I do know that C++ still has some oddities (hopefully those are being fixed with the new toolchain setup in the works) that makes debugging them very painful in some instances on the Flipper.

**Comment by kbembedded** [comment]
Latest round of updates brings a bunch of things together.

Gen i and ii trades fully functional again (there were some breakages over time)
Assets now loading from SD card. Will need more changes when final sprite assets come together
Forced synchronization of trade states, i.e. Back disabled for most things, press and hold back to force go back a screen.
All gen ii tunables are set up and working (minus egg, but, I left notes in place to handle eggs later if there is demand for it)
There are a few more things I want to clean up in code before doing a final clean/rebase and moving on to Mystery Gift

**Comment by kbembedded** [comment]
Gen II trade mostly locked in at this point. There may need to be some small tweaks, but, for anyone watching this PR; please test and see what you can break :smile: 

Starting on Mystery Gift support now. Getting the MALVEKE pinout to not break the OK button is on my list when I need a break from IR. And I think I can probably implement the "save default pinout" option pretty easily now that I've worked with loading data from the SD card.

Those, and then sprites are all that remain.

**Comment by kbembedded** [comment]
Mystery Gift support is going to be kicked down the road. There are complexities with the current IR libraries that would make the code a bit of a nightmare. I either need to spend time to get a better grasp of the IR system, or may need to consider adding some support to the flipper API.

**Comment by fexed** [comment]
Testing the Gen II trade with an italian copy of Pokémon Gold, building the fap with the Unleashed firmware, I get stuck on the "waiting" screen just after the trade ended :(

Update: looks like the issue is on the Funny Playing FPGBC side, tested with an original GBC and works flawlessly

**Comment by EstebanFuentealba** [comment]
> Testing the Gen II trade with an italian copy of Pokémon Gold, building the fap with the Unleashed firmware, I get stuck on the "waiting" screen just after the trade ended :(
> 
> Update: looks like the issue is on the Funny Playing FPGBC side, tested with an original GBC and works flawlessly

Hi @fexed In your FPGBC, what value do you have set for CLKSPD?

**Comment by fexed** [comment]
> > Testing the Gen II trade with an italian copy of Pokémon Gold, building the fap with the Unleashed firmware, I get stuck on the "waiting" screen just after the trade ended :(
> > Update: looks like the issue is on the Funny Playing FPGBC side, tested with an original GBC and works flawlessly
> 
> Hi @fexed In your FPGBC, what value do you have set for CLKSPD?

I don't think that is something I have control on. I did not modify it, and I'm on firmware version 1.08 (which is closed source as far as I know)

Note: after some retrying, I managed to succesfully trade a Pokémon. I was debugging adding some logs when it happened, so indeed a slightly wrong clockspeed seems to be the issue. IIRC the FPGBC doesn't run at exactly 100% but slightly less/more (can't remember rn) and that may be related, too.

**Comment by kbembedded** [comment]
> Update: looks like the issue is on the Funny Playing FPGBC side, tested with an original GBC and works flawlessly

Interesting.


> In your FPGBC, what value do you have set for CLKSPD?

> Note: after some retrying, I managed to succesfully trade a Pokémon. I was debugging adding some logs when it happened, so indeed a slightly wrong clockspeed seems to be the issue. IIRC the FPGBC doesn't run at exactly 100% but slightly less/more (can't remember rn) and that may be related, too.

From what I understand of the FPGBC (I've never used one) and the EXT link interface hardware is that this shouldn't be an issue, even if you crank the CPU clock speed up to max. The short technical answer is its a giant shift register and in the case of the trade tool, it forces the gameboy to drive it. The FPGBC wouldn't (well, _shouldn't_) exceed what the established clock rates are. The GBC can do different rates, up to 500some kHz, but even this wouldn't overwhelm the flipper side in processing data. Those rates are also dependent on the game, and as far as I can tell Pokemon G/S/C still only ever runs at the base 8192 Hz.


> Testing the Gen II trade with an italian copy of Pokémon Gold

Do you have a copy of a Gen I game to test a trade with? Either with the latest trade tool release, this dev branch, etc.

Can you take a video of the trade (Gen II at the very least, and Gen I if you can as well) and upload it somewhere so I can take a look at both the flipper and gameboy while the trade happens?


I might move this to an Issue and have to get a hold of an FPGBC to dig further.

**Comment by fexed** [comment]
Sorry for the trouble. As I was recording the Gen II video I think I found out why it didn't work this morning. It looks like the EXT port of the FPGBC is somehow slightly loose compared to (at least my) original GBC. The cable moves a little, and as we all know this kind of serial communication is not very happy to be moved around. By pushing the cable a bit more inside the EXT port of the FPGBC I managed to trade Pokémons without issues a few times.
I performed the test with Gen I (Pokémon Yellow) a couple of days ago and after some issues with the cable (which I handmade by stripping an original trade cable, as I am waiting for the Game Boy tools for the Flipper Zero 👀) I succesfully traded Pokémons. So no issue there, and I thought the problem was on Gen II side.

Anyways, I have all cartridges needed (even some jap and Gen III as well, for perhaps the future 👀) and all kinds of hardware (GB, GBC, GBA and FPGBC). If you need testing just lmk. I imagine that, given this was a false alarm, no video is needed? I can record it nonetheless if you need it.

**Comment by kbembedded** [comment]
> Sorry for the trouble. As I was recording the Gen II video I think I found out why it didn't work this morning. It looks like the EXT port of the FPGBC is somehow slightly loose compared to (at least my) original GBC. The cable moves a little, and as we all know this kind of serial communication is not very happy to be moved around. By pushing the cable a bit more inside the EXT port of the FPGBC I managed to trade Pokémons without issues a few times. I performed the test with Gen I (Pokémon Yellow) a couple of days ago and after some issues with the cable (which I handmade by stripping an original trade cable, as I am waiting for the Game Boy tools for the Flipper Zero 👀) I succesfully traded Pokémons. So no issue there, and I thought the problem was on Gen II side.

No worries! Glad you were able to figure it out. 

 
> Anyways, I have all cartridges needed (even some jap and Gen III as well, for perhaps the future 👀) and all kinds of hardware (GB, GBC, GBA and FPGBC). If you need testing just lmk. I imagine that, given this was a false alarm, no video is needed? I can record it nonetheless if you need it.

If you don't already have one of @EstebanFuentealba's MALVEKE boards on order, and are interested in doing some compatibility testing, shoot me an email at kris @ kbembedded.com and I'll get you one of my EXT interface boards for flipper so you don't have to mangle cables anymore 😄 

If you want to test different game boy hardware and Pokemon games and just drop notes here on what you tried and if you had any issues; all of that that would be great to get in documentation!

As an aside, JPN carts are currently not compatible with the Flipper trade tool. They use a different data format than all of the other western releases and you will end up with corrupt game data if you attempt a trade with a JPN release of Pokemon. At this time I don't have a JPN cart and am not terribly interested in implementing it. If it is something you are interested in tackling I can help if you have any questions on the current Trade Tool set up. I _do_ have plans for Gen III at some point, however.

**Comment by kbembedded** [comment]
With this latest update, older MALVEKE hardware that used to break the OK button after trade, no longer has that issue.

It was a very hacky workaround, but so far appears to be robust in latest OFW release.

If anyone running a CFW would be interested in testing, I'd love to know what you see there.

**Comment by kbembedded** [comment]
Home stretch! All sprites are complete. Just need rebase against #36 and update documentation with the new features.

**Comment by kbembedded** [comment]
Alright! Ready for review! @EstebanFuentealba take a look and let me know what you think. I did not update the README_es.md file, feel free to add that here or you can take care of it later. It is a pretty decent rewrite of all of the feature sections, the hardware section and how it works are unchanged. I also recorded a new video with 2.0 showing a gen II trade and added that as a reference.

**Pull request merged**
